language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
after_success: cat artifacts/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: UpV0tHu90soWlX6jR1RZlrf232DIVplDl2E4IH2iHVZGhrCCjef9Hlm4O9i3g6HOV+eeZJU4jlouhEURvWIMbWfnWmk4+cwifys6quW6b1iOnjZj58yXIxBMpeleDeV5KMctakyMQmGP7LYV//hhm4ZRbceO0Ww44Y+Gs4NUTbo=
deploy:
- provider: s3
  access_key_id:
    secure: mDBGdFnZeluq1ooyVe26s6KXo2mn72ZY90wwAIxNUYiDhTZ7+lbg+pRxlJU+tsFEO81OumoR1CwJQ1XuMLlJOWPqUhS6Sub2PwVVqshmij/eIFke+3eiBbnq+gkmninYU7gUIkSzF7FOmQIIKrIpDrQyHkYvlrz6M2/Z4Jd8yQs=
  secret_access_key:
    secure: Pdk4/CEvaBwtO6rM0yAsEEorp11i6jgkOnz3Rsa48jnY6yaMjB15/aESuNxQCP1HINZ8X5szSolJ/g+qdlIzBK8sbUAfJPbo8RRn9Mb3nncBsOK+pBHo1owh8cBZLVbUZLGM35mnspOhwxL43yexIBoEBmky0+k++QmjQiZe1DU=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: grunt-sh/master
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: master
- provider: s3
  access_key_id:
    secure: mDBGdFnZeluq1ooyVe26s6KXo2mn72ZY90wwAIxNUYiDhTZ7+lbg+pRxlJU+tsFEO81OumoR1CwJQ1XuMLlJOWPqUhS6Sub2PwVVqshmij/eIFke+3eiBbnq+gkmninYU7gUIkSzF7FOmQIIKrIpDrQyHkYvlrz6M2/Z4Jd8yQs=
  secret_access_key:
    secure: Pdk4/CEvaBwtO6rM0yAsEEorp11i6jgkOnz3Rsa48jnY6yaMjB15/aESuNxQCP1HINZ8X5szSolJ/g+qdlIzBK8sbUAfJPbo8RRn9Mb3nncBsOK+pBHo1owh8cBZLVbUZLGM35mnspOhwxL43yexIBoEBmky0+k++QmjQiZe1DU=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: grunt-sh/develop
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: develop